/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snudh;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@EnableEurekaServer
@RestController
public class discoveryApp {
  public static void main(String[] args) {
    // System.out.println(new App().getGreeting());
    SpringApplication.run(discoveryApp.class, args);
  }

  @GetMapping("/api/hello")
  public String home() {
    return "Hello Docker World";
  }
}
