CREATE DATABASE DOHBEDOH;

USE DOHBEDOH;

CREATE TABLE CONTACT (
	CONTACT_ID SMALLINT UNIQUE NOT NULL,
	CONTACT_PHONE_NUMBER VARCHAR(12) NOT NULL,
	CONTACT_FAX_NUMBER VARCHAR(12),
	CONTACT_EMAIL VARCHAR(30),
	PRIMARY KEY (CONTACT_ID)
);
CREATE INDEX CONTACT_ID_IDX ON CONTACT (CONTACT_ID);

CREATE TABLE ADDRESS (
	ADDRESS_ID SMALLINT UNIQUE NOT NULL,
	ADDRESS_NUMBER VARCHAR(4) NOT NULL,
	ADDRESS_LINE_1 VARCHAR(20) NOT NULL,
	ADDRESS_LINE_2 VARCHAR(20),
	ADDRESS_ZIP_CODE VARCHAR(5) NOT NULL,
	ADDRESS_CITY VARCHAR(20) NOT NULL,
	ADDRESS_STATE VARCHAR(20) NOT NULL,
	ADDRESS_COUNTRY VARCHAR(20) NOT NULL,
	PRIMARY KEY (ADDRESS_ID)
);
CREATE INDEX ADDRESS_ID_IDX ON ADDRESS (ADDRESS_ID);

CREATE TABLE COMPANY (
	COMPANY_ID SMALLINT UNIQUE NOT NULL,
	COMPANY_NAME VARCHAR(32) NOT NULL,
	COMPANY_ADDRESS_ID SMALLINT NOT NULL,
	COMPANY_CONTACT_ID SMALLINT NOT NULL,
	PRIMARY KEY (COMPANY_ID),
	CONSTRAINT FOREIGN KEY (COMPANY_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT FOREIGN KEY (COMPANY_CONTACT_ID) REFERENCES CONTACT(CONTACT_ID)
);
CREATE INDEX COMPANY_ID_IDX ON COMPANY (COMPANY_ID);

INSERT INTO CONTACT (CONTACT_ID, CONTACT_PHONE_NUMBER, CONTACT_FAX_NUMBER, CONTACT_EMAIL)
VALUES(
	1,
	'0412345678',
	'0412345679',
	'office@company1.com'
);
INSERT INTO CONTACT (CONTACT_ID, CONTACT_PHONE_NUMBER, CONTACT_FAX_NUMBER, CONTACT_EMAIL)
VALUES(
	2,
	'0423456789',
	'0423456780',
	'office@company2.com'
);

INSERT INTO ADDRESS (ADDRESS_ID, ADDRESS_NUMBER, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_ZIP_CODE, ADDRESS_CITY, ADDRESS_STATE, ADDRESS_COUNTRY)
VALUES
(
	1,
	'123',
	'Main St',
	'Floor 17',
	'4000',
	'Brisbane',
	'QLD',
	'Australia'
);

INSERT INTO ADDRESS
(
	ADDRESS_ID,
	ADDRESS_NUMBER,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	ADDRESS_ZIP_CODE,
	ADDRESS_CITY,
	ADDRESS_STATE,
	ADDRESS_COUNTRY
)
VALUES
(
	2,
	'123',
	'Main St',
	'Floor 5',
	'4000',
	'Brisbane',
	'QLD',
	'Australia'
);

INSERT INTO COMPANY
(
	COMPANY_ID,
	COMPANY_NAME,
	COMPANY_ADDRESS_ID,
	COMPANY_CONTACT_ID
)
VALUES
(
	1,
	'Allan Corporation Pty Ltd',
	1,
	1
);

INSERT INTO COMPANY
(
	COMPANY_ID,
	COMPANY_NAME,
	COMPANY_ADDRESS_ID,
	COMPANY_CONTACT_ID
)
VALUES
(
	2,
	'Kaichu Corporation Pty Ltd',
	2,
	2
);