/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snudh;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class discoveryAppTest {
    @Test void appHasAGreeting() {

    }
}
