

GET http://localhost:8080/hello
####


GET http://localhost:8080/status
####


GET http://localhost:8081/hello
####

GET http://localhost:8081/hi
####

GET http://172.31.37.55:9411/api/v2/spans?serviceName=spring-micrometer-tracing-demo
####


