spring:
  application.name: session.ex

  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID

      # 세션의 유효 시간을 지정합니다(단위: 초).
      timeout: 3600

  cache:
    type: redis
  session:
    store-type: redis
  redis:
    host: 172.31.37.51
    port: 6370
    password: