/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snudh.psv;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest
@ActiveProfiles("test")
class AppTest {
  @Test
  void main() {
  }
}
