server:
  port: ${PORT:8041}

spring:
  application:
    name: hwan

  main.banner-mode: off

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:sybase:Tds:172.16.90.236:3000/ocs?charset=iso_1&JAVA_CHARSET_MAPPING=ms949
    #url: jdbc:oracle:thin:@172.31.1.31:1521/ORAPW
    url: jdbc:oracle:thin:@172.30.16.235:1521/ORAPW
    #username: ocs
    #password: ocs123
    username: pwis
    password: pwis123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true;

eureka:
  instance:
    # 서비스의 호스트 이름이 아닌, IP 주소를 Eureka Server에 등록할지 여부
    preferIpAddress: true
    ip-address: ${IP_ADDR:172.31.37.51}

    instance-id: ${eureka.instance.ip-address}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://172.31.37.51:9988/eureka}

#logging.config: classpath:log4j2.xml      # log4j2 설정파일 경로 설정
logging:
  config: classpath:config/log4j2-dev.xml

management.endpoints.web.exposure.include: "*"
