/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snudh;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class hwanApp {
  //private final static Logger log = LogManager.getLogger(ocsApp.class);

  public static void main(String[] args) {
    SpringApplication.run(hwanApp.class, args);
  }

  @GetMapping("/api/hello")
  public String home() {
    //log.warn("HELLO!");
    return "Hello Docker World";
  }
}
