spring:
  application:
    name: test-program

  profiles:
    active: dev


logging:
  register-shutdown-hook: false
  config: classpath:logs/log4j2.xml
  # level:
  #   root: info
  #   org.study.runner: trace