server.port: ${PORT:9988}

## Eureka Client Configuration
eureka:
  instance.hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:${server.port}/eureka}
  # server:
  #   서버가 요청을 받기 전 대기할 초기 시간(ms)
  #   default 5분 : 실무에서는 보통 모든 서비스가 등록 되길 기다리기 위해 5분 후 정보를 공유
  #   개인 프로젝트인 만큼 빠른 등록을 위해 5ms로 설정
  #   wait-time-in-ms-when-sync-empty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.snudh : DEBUG
