spring:
  main:
    web-application-type: NONE

  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mariadb://172.31.37.55:3401/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: sdman
    password: snudh!v123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.engine.spi: TRACE