server.port: ${PORT:8021}

spring:
  application.name: alim
  profiles.active: dev

  main.banner-mode: off

eureka:
  instance:
    # 서비스의 호스트 이름이 아닌, IP 주소를 Eureka Server에 등록할지 여부
    preferIpAddress: true
    ip-address: ${IP_ADDR:172.31.37.51}

    instance-id: ${eureka.instance.ip-address}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://172.31.37.51:9988/eureka}

#logging.config: classpath:log4j2.xml      # log4j2 설정파일 경로 설정
logging:
  config: classpath:config/log4j2-dev.xml

management.endpoints.web.exposure.include: "*"