/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snudh;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@EnableAsync
@SpringBootApplication
@RestController
public class AlimApp {
    public static void main(String[] args) {
      SpringApplication.run(AlimApp.class, args);
    }

    @GetMapping("/api/hello")
    public String home() {
      return "Hello Docker World";
    }
}
